name: 'data_lab_new'
version: '1.0.0'
config-version: 2

profile: 'data-lab-new'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

models:
  jaffle_shop:
    +materialized: table
tests:
  +store_failures: true
